INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_RADIATIONPATTERN radiationpattern)

FIND_PATH(
    RADIATIONPATTERN_INCLUDE_DIRS
    NAMES radiationpattern/api.h
    HINTS $ENV{RADIATIONPATTERN_DIR}/include
        ${PC_RADIATIONPATTERN_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    RADIATIONPATTERN_LIBRARIES
    NAMES gnuradio-radiationpattern
    HINTS $ENV{RADIATIONPATTERN_DIR}/lib
        ${PC_RADIATIONPATTERN_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RADIATIONPATTERN DEFAULT_MSG RADIATIONPATTERN_LIBRARIES RADIATIONPATTERN_INCLUDE_DIRS)
MARK_AS_ADVANCED(RADIATIONPATTERN_LIBRARIES RADIATIONPATTERN_INCLUDE_DIRS)

